# Generated by Django 4.2.26 on 2025-11-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('menu_name', models.CharField(help_text='Unique name for the menu (e.g., "main_menu", "sidebar_menu")', max_length=100, verbose_name='menu name')),
                ('url', models.CharField(blank=True, help_text='Explicit URL (e.g., "/about/", "/contact/")', max_length=200, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, help_text='Named URL pattern from urls.py (e.g., "about_page", "product_list")', max_length=100, verbose_name='named URL')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['menu_name', 'order', 'name'],
            },
        ),
    ]
